##
## ENV: TEST
##

service:
  message: Hello, World

spring:
  jpa:
    hibernate:
      ddl-auto: update # Remove when developing with config dev on container.
  sql:
    init:
      mode: never # Remove when developing with config dev on container.
  datasource:
    url: jdbc:mysql://localhost:3306/plumbit?createDatabaseIfNotExist=true
    username: plumbit-tcu
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver