service:
  message: Hello, World

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  sql:
    init:
      mode: never

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: plumbit
  resource: plumbit-client
  public-client: true
  security-constraints:
    - authRoles:
      - user
      securityCollections:
      - patterns:
        - /property/*
  principal-attribute: preferred_username