##
## ENV: DEV
##

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:plumbit
    username: sa
    password: sa # VAULT VALUE
  h2:
    console:
      enabled: true